[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["Ray Chen <ray@raychen.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^9.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
