version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.11.0
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole:rw"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d:rw"
