version: "3"
services:
  unifi-network-application:
    container_name: unifi-network-application
    image: lscr.io/linuxserver/unifi-network-application:latest
    restart: unless-stopped
    depends_on:
      - unifi-db
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 1900:1900/udp #optional
      # - 8843:8843 #optional
      # - 8880:8880 #optional
      # - 6789:6789 #optional
      # - 5514:5514/udp #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      # - MEM_LIMIT=1024 #optional
      # - MEM_STARTUP=1024 #optional
      # - MONGO_TLS= #optional
      # - MONGO_AUTHSOURCE= #optional
    networks:
      - unifi-network
    volumes:
      - "./data:/config:rw"

  unifi-db:
    container_name: unifi-db
    image: docker.io/mongo:4.4.26
    restart: unless-stopped
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=unifi
    # - MONGO_INITDB_ROOT_PASSWORD=unifi
    networks:
      - unifi-network
    volumes:
      - "./mongodata:/data/db:rw"
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:rw"

networks:
  unifi-network:
    driver: bridge
