---
- name: Deploy UniFi Network Application
  hosts: gallifrey
  become: true
  tasks:
    - name: "Set service name"
      set_fact:
        service_name: "unifi-network-application"

    - name: Setup service
      ansible.builtin.import_tasks:
        file: "../../ansible/tasks/setup_service.yml"
