version: "3"

networks:
  observability:
    driver: bridge

services:
  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter:v1.7.0
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - observability
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    restart: unless-stopped
    privileged: true
    networks:
      - observability
    ports:
      - 8008:8080
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/cgroup:/cgroup:ro"

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.96.0
    restart: unless-stopped
    networks:
      - observability
    ports:
      - 8428:8428
    volumes:
      - "./victoriametrics:/etc/vm:rw"
      - "./vmdata:/storage"
    command:
      - "-promscrape.config.strictParse=false"
      - "-promscrape.config=/etc/vm/prometheus.yml"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2
    restart: unless-stopped
    user: "$UID:$GID"
    networks:
      - observability
    ports:
      - 3003:3000
    volumes:
      - "./grafana/data:/var/lib/grafana:rw"
      - "./grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "./grafana/datasources:/etc/grafana/provisioning/datasources"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
