global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: 2s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 2s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]
