---
- name: Setup Gallifrey
  hosts: gallifrey
  become: true
  tasks:
    - name: Install core packages
      apt:
        state: present
        update_cache: yes
        pkg:
          - ntp
          - ca-certificates
          - curl
          - rsync
          - dnsutils
          - gnupg
          - software-properties-common
          - python3

    - name: Set timezone to UTC
      timezone:
        name: Etc/UTC

    - name: Make sure ntp is started
      service:
        name: ntp
        state: started

    - name: Disable IPv6 - sysctl
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Disable IPv6 - modprobe
      lineinfile:
        dest: /etc/modprobe.d/blacklist.conf
        line: "blacklist ipv6"
        mode: "0644"
        create: true

    - name: Docker - Add GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - Add apt repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Docker - Install
      apt:
        update_cache: yes
        state: present
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Docker - Add user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker

    - name: Docker - Ensure service is running
      service:
        name: docker
        state: started

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name:
          - "docker==6.1.3"
          - "docker-compose"
        extra_args: --break-system-packages # :-/
