---
- name: Deploy nginx-certbot
  hosts: gallifrey
  become: true
  tasks:
    - name: "Set service name"
      set_fact:
        service_name: "nginx-certbot"

    - name: Setup service
      ansible.builtin.import_tasks:
        file: "../../ansible/tasks/setup_service.yml"
